### ISSUE TITLE
[Just curious] What kind of RCS do software engineers in highly confidential and/or secret projects use?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#122]
For example, like in government agencies, the military, or even top and/or big companies like FaceBook.

I am sure a government agency also requires the expertise of software engineers and developers. Perhaps, since some of such projects are high-stakes and top-secret, you would not find them hosting on websites like GitHub, BitBucket, Jenkins, GitLab or etc... Given the open-source nature of the server that the repositories are hosted on. Even if repository settings can be set to private, or even the organization to be made "secret", how much can they trust it?

I know it was mentioned in today's lecture that Mozilla used (_or still uses_) Mercurial.

Actually, I think @damithc would be one of those who could possibly answer this question or at least offer some inputs, given his experience in the software engineering industry in the past? Haha~

P.S. Pardon me if this question is a little irrelevant to the current syllabus or even nonsensical, but I am just curious :P

**Comment by ghost** [comment]
Maybe for government agencies and the military, we aren't even supposed to know.

For Facebook, maybe it depends... Perhaps some of their SE projects are open-source and they even allow issues and bugs to be reported, or even PRs (or the equivalent in whatever kind of automation server they are using) to be sent in.

For Mozilla, definitely, they are open-source.

**Comment by rongjiecomputer** [comment]
Government agencies, military and some private companies that don't do open-source might still be using similar technology. Github, Gitlab, Visual Studio Team Services, Google Cloud Source Repository and so on all offer Enterprise users code hosting stacks that can be deployed in the cloud (GCP/Azure) or even self-hosted in the organization itself to keep things private. These solutions are usually still Git-based.

Sometimes, private company might choose not to use Git, Mercurial or other open-source VCS when these tools do not fit the company's need or the company's desire to manage the toolchain head-to-toe. Google satisfies both criteria and is well-known for its powerful in-house tools:

- Piper: Distributed VCS designed to be able to handle Google's 2BLoC internal monolithic repo (Git will probably be too slow). Open-source projects like Chromium still use Git.
- [Copybara](https://github.com/google/copybara): Do code transformation so that internal repo and the open-sourced version of it are in-sync. Tensorflow and Bazel use this heavily when open-sourcing internal code to the public.
- [Critique](https://opensource.google.com/docs/glossary/#critique): Internal code review tool similar to [Gerrit](https://en.wikipedia.org/wiki/Gerrit_(software)) (which Google is the original author).

** The list is not exhaustive of course, Google interns will probably know more.

Reference: https://ai.google/research/pubs/pub45424

**Comment by ghost** [comment]
Thanks for your very informative answer!

What if it is in China or North Korea? Where Google is banned?

**Comment by rongjiecomputer** [comment]
> What if it is in China or North Korea? Where Google is banned?

Self-hosting is still an option. Github, Gitlab, VSTS etc. are not banned in China, so China companies can download their code-hosting software for deployment just fine.

- https://enterprise.github.com/releases/2.15.0/download
- https://about.gitlab.com/pricing/#self-managed
- https://marketplace.visualstudio.com/items?itemName=ms.build-release-private-pipelines

Note that Google is not entirely banned in China. Google Translate has never been banned in China. And technically China company can also use proxy to connect to GCP servers in Hong Kong, though performance might not be great.

Random trivia: current core *maintainer* of Git is a Googler: [Junio C Hamano](https://en.wikipedia.org/wiki/Junio_Hamano).
