### ISSUE TITLE
No invitation to PE issue trackers due to administrative issues.

### ISSUE THREAD

**Issue by AlecNgZW** [nus-cs2103-AY1819S1/forum#145]
I do not have an invitation to the issue tracker and the page returns 404

**Comment by HEARTOFAL1ON** [comment]
Because the dry run is over and the issue tracker has been closed :o

As for the invitation, I'll leave it to the teaching team to answer :)

By no invitation received, do you mean _at all_? Did you check your spam folder in your **email address associated with your Github account** to see if it's there?

This is because you were supposed to receive an email from cs2103@comp.nus.edu.sg in the afternoon.

![image](https://user-images.githubusercontent.com/35895966/47914743-a9a27300-dedb-11e8-8e31-134907f4f5f9.png)

**Comment by damithc** [comment]
Invitation sent just now. Please accept before week 13 PE. You will not be able to access the pe-dry-run repo now as it has been closed.

**Comment by damithc** [comment]
@AlecNgZW please close this issue after accepting the invitation.

**Comment by AlecNgZW** [comment]
Thank you prof, received and accepted invitation!
