### ISSUE TITLE
AddressBookSystemTest.java error

### ISSUE THREAD

**Issue by ryantanwk** [nus-cs2103-AY1819S1/forum#173]
Hi prof,

I am suddenly getting assertion failures for FindCommandSystemTest, line 79, case: undo rejected and SelectCommandSystemTest, line 42, case: undo rejected. 

I have never changed the files and only recently got these errors. Based on my debugging it seems like function assertApplicationDisplaysExpected in AddressBookSystemTest is not capturing input from the command box.

How should I proceed? I am worried because I am not able to merge my PR since the test is failing and demo is approaching.

Could I look for you some time on Monday perhaps?

Thank you,

Sincerely,
Ryan

**Comment by yamgent** [comment]
> Based on my debugging it seems like function assertApplicationDisplaysExpected in AddressBookSystemTest is not capturing input from the command box.

That method is used by a lot of test cases, so it seems possible that your app's `UndoCommand` and `RedoCommand`'s behaviour might have accidentally been altered.

Did you try running the failing test case _without_ headless mode (using IntelliJ)? You may be able to spot visually what went wrong. Try comparing the visuals with a previous commit that has the same test cases passing to see if there's any difference in the behavior.

**Comment by ryantanwk** [comment]
Hi, Yes, I have been debugging without headless mode. By looking at the expected and actual of the failing tests, it shows that the actual parameter is empty

**Comment by yamgent** [comment]
> it shows that the actual parameter is empty

Yes, that is because `undo` has succeed. Whereas with the original passing behavior, the `undo` should fail because none of the executed commands in the system test are supposed to be undo-able.

That indicates that something must have modified the `VersionedAddressBook`, which `UndoCommand` uses to see whether there are any commands to be undone. It can undo if a new state is added using `VersionedAddressBook#commit()`.

If we were to put a breakpoint on the commit method, you will realise that a new commit is always been executed on launch, because `setNotification()` is always being called when the application is launched.

```java
    /**
     * Configure notification based on existing user preferences in preferences.json
     */
    private void setNotification(UserPrefs prefs) {

        model.updateNotificationPref(prefs.getGuiSettings().getNotificationIsEnabled());
        model.updateFavourite(prefs.getGuiSettings().getFavouriteEvent());
        model.commitAddressBook();   /* <---------------------------- */

        if (model.getNotificationPref()) {
            if (model.getFavourite() != null) {
                NotificationWindow.display(NOTIFICATION_FAVOURITE_TITLE, model.getFavourite());
            } else {
                NotificationWindow.display(NOTIFICATION_DEFAULT_TITLE, NOTIFICATION_DEFAULT_TEXT);

            }
        }
    }
```

This means that the user can always execute `undo`, even though he or she did not even execute a single command yet.

Decide whether the commit is necessary, or whether the call to `setNotification()` is too early. If the commit is unnecessary, remove the call to `commitAddressBook()`. Or if it is necessary, change the test behaviour in `FindCommandSystemTest` and `SelectCommandSystemTest` so that the test case tests that your `undo` and `redo` are successful (i.e. `assertCommandSuccess()` instead of `assertCommandFailure()`)

**Comment by ryantanwk** [comment]
Hi, Understood. Thank you taking the time to explain clearly.
