### ISSUE TITLE
The ppp is not displayed in project list

### ISSUE THREAD

**Issue by ZZG229** [nus-cs2103-AY1819S1/forum#189]
Hi prof,

I realize that there is some problem with the naming of my ppp file and it cannot be displayed in the project list. Thus, may I know if it is possible for me to make a pr and update the naming of the file so that my ppp can be accessed from the project list? Thanks!

**Comment by ZZG229** [comment]
In addition, if I am allowed to do so, may I know will I be penalized for this change?

**Comment by damithc** [comment]
You can fix it without a penalty.

**Comment by ZZG229** [comment]
Hi prof, I renamed the file and I can access it from my team's aboutus page. However, in the project list, it still shows that my ppp cannot be found.

![image](https://user-images.githubusercontent.com/39242455/48604003-56d4bb00-e9b3-11e8-9d77-396a5c7a0895.png)

Hence may I know what went wrong?
Thanks!

**Comment by yamgent** [comment]
When I visited your page just now it gave me a 404, but now it seems to work fine.

Might be an isolated temporary GitHub issue for your page.

However, your fellow teammate's URL is linked wrongly. It links to `Pratyushghosh.html` instead of `pratyushghosh.html` (all small letter case). Some parts of the URL are case-sensitive depending on the web server involved.

**Comment by damithc** [comment]
Seems to work now.
