### ISSUE TITLE
(Auto-publishing of docs) Can we use the same personal access token for other repos?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#39]
According to steps from [here](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/project-w06-mid-v11.html), I already set up auto-publishing of docs for our _teamorg's_ `main` repo.

Also from [here](https://nus-cs2103-ay1819s1.github.io/addressbook-level4/UsingTravis.html#enabling-auto-publishing-of-documentation): My question is whether we could use the same personal access token like for e.g. `GITHUB_TOKEN` for our forked repos of ABL3, ABL2 and ABL1?

**Comment by azhikai** [comment]
Since ABL1-3 is just for achieving LOs, I don't really see the need to set up auto publishing of docs for them. 

In your case, you can instead generate the token using your own personal account for ABL1-3, since it'll be your local fork and you're the only one having write access to it. You _could_ use the same token, but then it poses a security risk (because you can perform Git operations using the token, well, depending on the scope defined as well) as already mentioned in the set up guide.

**Comment by ghost** [comment]
Thank you. I will close this :)

I don't think there is any harm generating more personal access tokens too
