### ISSUE TITLE
Refactoring Inline Method

### ISSUE THREAD

**Issue by kohchihao** [nus-cs2103-AY1819S1/forum#4]
Hi all, I've got a question to ask regarding **Refactoring Inline Method**

I've got these 2 methods.
```
private static String getMessageForSuccessfulAddPerson(HashMap<PersonProperty, String> addedPerson) {
    return String.format(MESSAGE_ADDED,
        getNameFromPerson(addedPerson), getPhoneFromPerson(addedPerson),
        getEmailFromPerson(addedPerson));
}

```

```
private static String getNameFromPerson(HashMap<PersonProperty, String> person) {
    return person.get(PersonProperty.NAME);
}
```

Would it be okay to refactor the 1st method to become 

```
private static String getMessageForSuccessfulAddPerson(HashMap<PersonProperty, String> addedPerson) {
    return String.format(MESSAGE_ADDED,
        addedPerson.get(PersonProperty.NAME), addedPerson.get(PersonProperty.PHONE),
        addedPerson.get(PersonProperty.EMAIL));
}
```
Reference :[https://refactoring.com/catalog/inlineMethod.html]( https://refactoring.com/catalog/inlineMethod.html)

**Comment by damithc** [comment]
For now, let me just say that it is a case of matching pros against cons. Let's see if anyone else can pitch in with the various pros and cons they can see.

**Comment by jackedelic** [comment]
I will lean towards the post-refactored approach, which is more OO style. Say I want to have Employee as subclass of Person, and I want to be able to get his salary. In the original, pre-refactored style, we would have to define getSalaryFromEmployee in AddressBook. A more OO approach would be - addedEmployee.get(...Salary). With any new subclass and its associated methods, we don't define the methods in AddressBook anymore, we define in the subclass itself since they belong only to the subclass. Hence I would say the post refactored approach is more maintainable and conceptually intuitive.
I would love to hear from others what the possible cons to this approach are.

**Comment by wn** [comment]
I would first create a new method in person:
```
public parseMessageForPerson(String message) {
    return String.format(message,
        this.name, this.phone,
        this.email);
}
```
Then add:
```
private static String getMessageForSuccessfulAddPerson(HashMap<PersonProperty, String> addedPerson) {
	return addedPerson.parseMessageForPerson(MESSAGE_ADDED);
}
```
Seems more dry.

Oops, I just realised that addressbook1 wants person to be a hashmap. But wouldn't a class makes more sense? If we want to add more properties to person, its very cumbersome to loop through every person stored in an array to add that property. If it was a class, we can just write a migration to set the new property to null. 

For addressbook 1, it wouldn't really matter which one is choosen as they are all in the same file. However, I will prefer the first one as we are abstracting the implementation of name/phone/email from the client.

**Comment by azhikai** [comment]
// Might be a little off-topic here with regards to inline refactoring. 

I suppose Chi Hao's method would work and with regards to inline refactoring, that'd be what I'd have done as well. But putting that aside and consider this: what if the person property expanded to include 10 more properties? In this case, you'd have to update various area of the codes to reflect this changes. 

Since we're restricted to using procedural style only, maybe it would be a good idea of have this two methods (overloaded it)?

```java
    /**
     * Returns given person's property.
     *
     * @param person whose property you want.
     */
    private static String getPersonInfo(HashMap<PersonProperty, String> person,
            PersonProperty personProperty) {
        return person.get(personProperty);
    }
```
Usage: `getPersonInfo(person, PersonProperty.NAME)`

```java
    /**
     * Returns a String containing the all the person's properties.
     *
     * @param person whose properties you want.
     */
    private static String getPersonInfo(HashMap<PersonProperty, String> person) {
        // Form the string of this person's info...    
        return ""; // Returns said string...
    }
```
Usage: `getPersonInfo(person)`

So in Chi Hao's attached code, it can be used like this:

```java
private static String getMessageForSuccessfulAddPerson(HashMap<PersonProperty, String> addedPerson) {
    return String.format(MESSAGE_ADDED, getPersonInfo(addedPerson));
}
```

This way, I think it's much cleaner, and when the person's property expand to even 1000 properties, all we need to change is one method's body and it applies to everywhere else.

**Comment by YuPeiHenry** [comment]
I think keeping the getNameFromPerson method separate makes extending the Address Book more flexible. For an example, if there was a findByPhoneNumber method, and you want to know the name of the person with the matching phone number, you can reuse the getNameFromPerson.

**Comment by YipZong** [comment]
To me, if we are using the following methods
```
getNameFromPerson(addedPerson)
getPhoneFromPerson(addedPerson)
getEmailFromPerson(addedPerson))
```

1. We have to write multiple similar methods if we have more 'properties'.  It seems tedious but I think our hardworking IDE can do the job for us.

2.This is more OOP where we can hide the data. More secured? 

3.We can also adjust the access modifers (private, public, protected, and private) . More flexible. This cannot be achieved if we use

`addedPerson.get(PersonProperty.NAME)`

4.In case we want to do more than just getting the value, we can always add more actions in the getter method. This is a bad practice, but we do enjoy some flexibility here.

**Comment by damithc** [comment]
Thanks for all who pitched in with their inputs. AB-1 is written in non-OOP fashion, which can affect this scenario e.g., one of the option can appear to be more OOP (which is a good thing) but then the code is written to be non-OOP on purpose. Anyway, being able to see many different pros and cons is the important thing. There is no absolutely right choice; even if there is, the code can evolve in unexpected directions in the future, which can make the option that looked worse to turn out to be the better choice under the new circumstances.

**Comment by damithc** [comment]
Closing as the question seems to be answered. Feel free to reopen if not.
