### ISSUE TITLE
Question on Storage component architecture

### ISSUE THREAD

**Issue by anubh-v** [nus-cs2103-AY1819S1/forum#40]
Hi all,
I have a question about the design of the Storage component's architecture.

![image](https://user-images.githubusercontent.com/35621759/45929870-37f51200-bf8a-11e8-89a7-e30cb363c1fb.png)

There are 3 classes I would like to focus on, in the above image
- `XmlAddressBookStorage`
- `XmlSerializableAddressBook`
- `XmlFileStorage` (not shown in the diagram, but it's also in the Storage component)

The XmlAddressBookStorage class is dependent on XmlFileStorage, as seen in the following code snippet
![image](https://user-images.githubusercontent.com/35621759/45929936-00d33080-bf8b-11e8-990d-3014c6973c0f.png)

My question: From the perspective of designing architecture, what's the reason to separate the `XmlSerializableAddressBook` and `XmlFileStorage` classes? 
I understand that `XmlSerializableAddressBook` is the "JAXB friendly" class that allows us to map the Addressbook XML data to a Java object representation.

However, `XmlFileStorage` only has static "utility" methods that ultimately call `XmlUtil` to do their work. Why not place these methods under `XmlSerializableAddressBook`?

I would like to understand the reasoning / principles being applied here.
I don't think it has to do with abstraction, since `XmlFileStorage` doesn't seem to be abstracting any details.
What do you guys think?

Thanks

**Comment by davidchoo12** [comment]
Just a guess, but maybe `XmlFileStorage` is for interfacing the storage component with `XmlUtils`.

Honestly I think the entire AddressBook 4 is overengineered. But I get the point is for us to learn to code in a large codebase. So maybe that's why there is so many "unnecessary" layers. "Unnecessary" as in feels unnecessary but is probably a good practice if the project were to grow bigger and handled by large teams.

**Comment by damithc** [comment]
@hidingmode is right, in that there may not be an actual need for this many levels of abstraction. Some design decisions that looked fine at the start may not apply anymore after the subsequent evolution of the code. For example, `XmlUtil` is meant to contain xml-related util methods that are usable by the rest of the app without needing to know about the `Storage` component, although the current `XmlUtil` doesn't seem to fit that intention.
It's a good thing to question these decisions and also feel free to change them. Just make sure you document the changes and the rationale. Reducing code and simplifying design are good things to do.

**Comment by pyokagan** [comment]
@hidingmode 
> Honestly I think the entire AddressBook 4 is overengineered.

Hmm, why would you think that? Do you have any other examples?

> But I get the point is for us to learn to code in a large codebase. 

We don't actually aim to make the codebase large just to simulate "a large codebase". If there is a way to slim down the codebase without sacrificing other aspects (e.g. testability, SRP etc.), and there are people who are willing to submit PRs for that, it would be great.

I'm very happy that this discussion came up by the way. I was very sad when [no one gave any feedback last semester](https://github.com/se-edu/addressbook-level4/issues/883) :-(

**Comment by anubh-v** [comment]
@pyokagan, thanks for the response.
What are your thoughts on the particular case I highlighted? 

> However, XmlFileStorage only has static "utility" methods that ultimately call XmlUtil to do their work. Why not place these methods under XmlSerializableAddressBook?

**Comment by davidchoo12** [comment]
@pyokagan
> Hmm, why would you think that? Do you have any other examples?

It's just a feeling based on my limited experience. I don't have a specific example but I can list a few things I might change if I am to code AB4.

Disclaimer: I'm more familiar with the MVC way of doing things, so my opinion might not apply to the case of AB4. Also, I'm not familiar with the aspects of testability, etc.

If I were to code AB4, some changes I might do:
- Instead of having a command class for each command, I will group some of them up, such as all the CRUD operations into 1 file, undo/redo/history into 1. Not sure what I would do with the other though.
- Put all the command strings into a file somewhere then have the code read the file.
- Only have AddressBook and Person as models. Person class will contain all the attributes and handle their validation.
- Only use json and no xml.

**Comment by pyokagan** [comment]
@anubh-v 
> However, XmlFileStorage only has static "utility" methods that ultimately call XmlUtil to do their work. Why not place these methods under XmlSerializableAddressBook?

Yes, I agree.

The code in question came from the original version of AB-4, which I understand was pretty rushed, so there's probably no explicit reason why it was done this way.

**Comment by pyokagan** [comment]
@hidingmode 

Thanks. You've given some interesting ideas. I'll respond to some of them here, but in order to not derail this thread I think we should bring it to Gitter or to a new issue after this :-)

> Instead of having a command class for each command, I will group some of them up, such as all the CRUD operations into 1 file, undo/redo/history into 1. Not sure what I would do with the other though.

Ehh, not sure how this would work. Each command is implemented as a command class so that LogicManager can execute commands without needing to know the exact underlying command (The command pattern). Would this proposed implementation retain this property?

Also, we used to have a similar situation with the parser code. Everything used to be inside one gigantic `Parser.java` file. It wasn't very fun to work with :-P https://github.com/se-edu/addressbook-level4/pull/272#issuecomment-279120552

E.g. from the commit message of https://github.com/se-edu/addressbook-level4/pull/272/commits/b443d880b041cabdbfdc6da7f82f7f520b1b3ef7

```
Parser class implements all different
command parsers as private methods within the Parser class.
Parser::parseCommand is responsible for performing an initial
parsing on the given input string and from there determine
the correct method to parse the String to.

This causes the Parser file to become very long
containing all command parser methods
and their associated helper methods that is only utilized in that
one method itself.
```

> Put all the command strings into a file somewhere then have the code read the file.

Don't quite understand this. Are we talking about command execution here? Storage?

> Only have AddressBook and Person as models. Person class will contain all the attributes and handle their validation.

The `Name`, `Phone`, `Email` etc. classes can be useful when we want to represent a valid name, phone, email etc. in isolation from any person.

We use that with `EditPersonDescriptor`, for example.

> Only use json and no xml.

Yes, this is a very good idea, especially since JDK 11 removes JAXB for good. Jackson also has a much better API design.

Maybe this could be a CS2103R project :-)

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.
