### ISSUE TITLE
Anybody managed to delete a Person field cleanly?

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1819S1/forum#60]
Anybody managed to delete a `Person` class field without breaking any tests? If yes, can share a link to the relevant commit here?

Another student has run into some trouble trying to delete a field and would like to see an example of how to do it. If your commit helps that student, your help will be acknowledged in his/her project (as per module policy about reuse).

**Comment by ghost** [comment]
I am not sure if this helps, but my group has decided to remove the `AddressBook` class and all other associated classes/codes in place of a new (_but still rather similar_) class. We have not fully implemented as we are planning to do so soon, and not sure if we would run into any problems or issues in the near future.

Which is why it is good to perform _frequent regression testing_ I guess :)

**Comment by davidchoo12** [comment]
@HEARTOFAL1ON do you also delete the tests?

**Comment by ghost** [comment]
We are also still in the process and actually, we created a new class (let's call it X) that is similar to the `AddressBook` class but in addition to the methods that the `AddressBook` class and its associated classes, we have also included our own methods.

This involves an extensive change of some codes in certain existing classes too such as `Model.java` if I do remember correctly.

However, we still kept and I think we are still intending to keep the `Person` class.

Regarding your questions about tests, we have not fully implemented the tests yet for our new class(es) and we are intending to fully test out soon (this is to follow the guidelines to test as much as possible I guess?)

Finally, the reason why we want to delete the `AddressBook` class and other classes not relevant to our project is because we would want to prevent confusion if you can follow my train of thoughts. Haha~

**Comment by YuPeiHenry** [comment]
My group replaced some fields with different classes such as email (String) with waitTime (int). Unfortunately there was some tests to be fixed, spanning more than 1 commit, due to the renaming of the fields (Look at the .xml files if you haven't).

**Comment by OrangeJuice7** [comment]
I haven't deleted a `Person` class field, but I have added a new one that works throughout. (Unfortunately, the PR is a mess so me or someone else in my group will be redoing it.)

From my experience, I would suggest Ctrl-Shift-F'ing one of the existing classes such as `Phone` or `Email`, and go through *everywhere* where those classes are used, initiated, referenced etc. Make sure that in those places, the class field that you want to delete is not there anymore.
There is a lot of manual construction of `Person`s (and `AddressBook`s) in the test case files (esp. testing if a valid `Person` can be constructed using invalid or missing parameters). Maybe you deleted the class field but you still have extra arguments in the test command strings.

In addition, the `Person` class has a method called `isSamePerson()` which says two `Person`s are equal iff their `Name` is equal and either their `Phone` or `Email` are equal (iirc). If the class field that you are deleting is one of these, make sure to update `isSamePerson()` accordingly as well. This will also affect the expected results from your test cases, not just comparison, but for filtering, editing, deleting etc.

Hope this helps.

**Comment by alexehrs** [comment]
Thank you all, I got it working now!
I used the ctrl-shift-F worflow by @FongYuan, and in the end I only had some small error with isSamePerson() which he also warned me about. Thank you very much!

**Comment by damithc** [comment]
> Thank you all, I got it working now!
> I used the ctrl-shift-F worflow by @FongYuan, and in the end I only had some small error with isSamePerson() which he also warned me about. Thank you very much!

Great. Thanks everyone who pitched in. :100:
