### ISSUE TITLE
Is there a reason why the Person model is immutable?

### ISSUE THREAD

**Issue by davidchoo12** [nus-cs2103-AY1819S1/forum#67]
As commented in Person.java line 14: `Guarantees: details are present and not null, field values are validated, immutable.`

**Comment by yamgent** [comment]
Good question. The se-edu (upstream AB-4) team decided that going immutable is the way, because it is easier to reason about what the code is doing, making coding much simpler. We do not have to worry about potential side effects from functions that handle `Person` objects (which may or may not be intentional), because their fields cannot be changed once initialized.

Of course, immutability has its pros and cons. I leave it to your team to research about them, and decide whether this is the direction your group wants to continue going forward. 😉

**Comment by ghost** [comment]
Interesting~ I am also curious how is it possible for Java developers to make a class immutable in the first place, but that can wait till next time :=)

Or maybe if it is necessary in my group project ;=)

**Comment by davidchoo12** [comment]
@yamgent 
Is it because of the requirement of versioning the address book?
So there is a need to make copies for every change and immutability ensures that all changes to any of the model will have to be made by making a copy of that model.
If I am removing the undo/redo feature (so no need for versioning any more), immutability will not be required. Right?

**Comment by yamgent** [comment]
@hidingmode 

It is not really about whether it being "required" or not, but I think I roughly get your point.

Think about it this way: is it possible to implement versioned address book _without_ immutability? Certainly yes! The most trivial way of realizing that possibility, is to take the current upstream AB-4 code, replace all `ReadOnlyAddressBook` with `AddressBook`, and make `Person`'s fields modifiable, while the rest of the code remains the same. That final result is proof that you don't need immutability to have a working versioned address book.

But making it immutable expose us to more potential bugs in the future as we expand the codebase, for reasons that I have mentioned in my previous post.

Therefore, my personal advice would be to stick to immutable `Person`, because:
* The codebase is already written this way, and time is limited. The team will accrue additional development costs if they deviate from the original design (e.g. existing tests may turn to become unreliable, because are written with the immutability assumption, and they don't test for changes in `Person` because YAGNI). This cost is quite an important consideration, given that the development timeframe is short (the final milestone is just a few weeks away).
* The codebase will evolve to become more complex. The team is expected to implement some enhancement features, which will definitely involve, directly or indirectly, the `Person`'s class. So even if the plan is to remove the undo/redo feature and implement something else, that "something else" could be a good enough reason to stick to the original design of immutability.

But that's just my humble opinion for a general scenario. Remember that at the end of the day, your team is the one developing the product, so there may be additional considerations that I may not be able to see from your viewpoint.

Hope that clarifies your doubt.

**Comment by damithc** [comment]
In this week lecture, we'll discuss _defensive coding_. Making things immutable unless there is a specific need to be mutable is a more defensive approach to coding i.e., it defends against the possibility of an object being modified by mistake.

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.
