### ISSUE TITLE
Git: Difference betwwen pull request and branch merge

### ISSUE THREAD

**Issue by YipZong** [nus-cs2103-AY1819S1/forum#9]
It seems that 
"PR (in GitHub) = merge (in SourceTree)" 
or more specifically
"PR = merge + inviting discussion" 
based on my understanding and basic research. 

Is this understanding correct?
Thank you!

**Comment by damithc** [comment]
_Pull Request_ is essentially a _request_ to _pull_ new code from one repo to another repo, made by the author of the new code. The `pull` needs to be followed by a `merge` for the code to become a part of the target code base. I guess that's why its called _merging a pull request_.

So, your understanding is correct: a PR is _merging with extra steps_. The extra steps facilitate the collaboration between code provider and and code receiver.

**Comment by azhikai** [comment]
Hi Yezhong,

No, that's not what PR entirely means. Please don't be confuse with PR and merge as they're both different process, but reviewing and approving a PR does lead to a merge. I'll try to explain it as layman as possible:

Assume I have my own public repo, let's call this repo `public-A`. You chanced upon it and realised that it's a cool project and want to contribute, but you don't have write access to it -- meaning, you can clone  `public-A`, but when you try to push your local changes to it, you'll get permission denied. So that won't be ideal! (You can try to clone any of the AB repo directly and you'll see what I mean).

So what'd be the workaround? Yes, to fork repo `public-A` to your own local GitHub, let's call this repo `fork-A`, clone it then work on it. Let's assume you added some cool stuffs on the `master` branch and then pushed it to GitHub (to `fork-A`, not `public-A`). Afterwards, it's time to make a PR (Pull Request)!

Because you don't have `write` access to `public-A`, you'll need to click on the "Make a pull request" button in `fork-A`, which will open up another page that compares the `master` branch of both `public-A` and `fork-A` and it'll indicate to you whether there's any merge conflicts, etc. From there, fill in the blanks (PR title, message, etc) and submit the PR! 

On my side, I'd have received that PR. I'll then review your code* and make sure it does what you say it does. Once I'm happy with it, I'll approve your PR and merge your changes into `public-A`. That is, think of PR as you, the contributor, telling the owner of the repo (me): "Please accept my changes to the code!". 

*Note: I excluded things like status check (passing CI build, etc), number of positive reviews needed, etc. Those are rather slightly more advanced stuffs which we'll get there later in the course.

**Comment by taneliang** [comment]
Some other tools like GitLab call PRs "merge requests", which are identical to PRs but viewed from a different perspective: you create a merge request to request someone to merge your code into their codebase. This alternative name might be more intuitive. An explanation of PRs/MRs can be found at https://stackoverflow.com/a/36666408/5281021

Also, you might want to note that branch merging is a feature of Git, but pull requests are a feature of GitHub. GitHub is basically a glorified Git remote and host that adds value through collaboration and social networking features that are not part of Git. In fact, you don't have to use GitHub at all for collaboration; the Linux kernel uses an email workflow where patches and discussions are sent over email. Because Git and GitHub are not the same thing, PRs can't be the same as merges.

**Comment by damithc** [comment]
Closing as the question seems to be answered. Feel free to reopen if not.
